version: '3.4'

services:
  books.api:
    image: ${DOCKER_REGISTRY-}booksapi
    build:
      context: .
      dockerfile: ./Books.API/Dockerfile
    depends_on:
      - seq
      - rabbit 
    ports:
      - 8080:80

  books.processor:
    image: ${DOCKER_REGISTRY-}booksprocessor
    build:
      context: .
      dockerfile: ./Books.BookProcessor/Dockerfile
    depends_on:
      - seq
      - rabbit 

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 8088:15672
      - 5672:5672

  seq:
    image: datalust/seq
    ports:
      - 5431:5431
      - 8089:80
    environment:
      - ACCEPT_EULA=Y